DjangoCRM/DjangoCRM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("myauth/", include("myauth.urls")),
    path("products/", include("productapp.urls")),
    path("ads/", include("adsapp.urls")),
    path("leads/", include("leadsapp.urls")),
    path("contracts/", include("contractsapp.urls")),
    path("customers/", include("customersapp.urls")),
    path("statistics/", include("statisticsapp.urls")),
]

DjangoCRM/adsapp/urls.py
from django.urls import path

from .views import (
    AdsCreateView,
    AdsDeleteView,
    AdsDetailView,
    AdsListView,
    AdsUpdateView,
)

app_name = "adsapp"

urlpatterns = [
    path("", AdsListView.as_view(), name="ads_list"),
    path("new/", AdsCreateView.as_view(), name="ads_create"),
    path("<int:pk>/", AdsDetailView.as_view(), name="ads_detail"),
    path("<int:pk>/edit/", AdsUpdateView.as_view(), name="ads_update"),
    path("<int:pk>/delete/", AdsDeleteView.as_view(), name="ads_delete"),
]

DjangoCRM/customersapp/urls.py
from django.urls import path

from .views import (
    CustomerCreateView,
    CustomerDeleteView,
    CustomerDetailsView,
    CustomerListView,
    CustomerUpdateView,
)

app_name = "customersapp"

urlpatterns = [
    path("", CustomerListView.as_view(), name="customers_list"),
    path("new/", CustomerCreateView.as_view(), name="customers_create"),
    path("<int:pk>/", CustomerDetailsView.as_view(), name="customers_detail"),
    path("<int:pk>/edit/", CustomerUpdateView.as_view(), name="customers_update"),
    path("<int:pk>/delete/", CustomerDeleteView.as_view(), name="customers_delete"),
]

DjangoCRM/leadsapp/urls.py
from django.urls import path

from .views import (
    LeadCreateView,
    LeadDeleteView,
    LeadDetailsView,
    LeadsListView,
    LeadUpdateView,
)

app_name = "leadsapp"

urlpatterns = [
    path("", LeadsListView.as_view(), name="leads_list"),
    path("new/", LeadCreateView.as_view(), name="leads_create"),
    path("<int:pk>/", LeadDetailsView.as_view(), name="leads_detail"),
    path("<int:pk>/edit/", LeadUpdateView.as_view(), name="leads_update"),
    path("<int:pk>/delete/", LeadDeleteView.as_view(), name="leads_delete"),
]

DjangoCRM/leadsapp/models.py
from adsapp.models import Ad
from django.db import models


class Lead(models.Model):
    """Сущность: потенциальный клиент"""

    full_name = models.CharField(max_length=255, verbose_name="Ф.И.О.")
    phone_number = models.CharField(max_length=12, verbose_name="Телефон")
    email = models.EmailField(unique=True, verbose_name="Email")
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name

DjangoCRM/leadsapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import Lead


class LeadsListView(PermissionRequiredMixin, ListView):
    """Список всех потенциальных пользователей"""

    permission_required = "leadsapp.view_lead"
    template_name = "leadsapp/leads_list.html"
    context_object_name = "leads"
    queryset = Lead.objects.prefetch_related("ad").all()


class LeadCreateView(PermissionRequiredMixin, CreateView):
    """Создание нового потенциального пользователя"""

    permission_required = "leadsapp.add_lead"
    template_name = "leadsapp/leads_create.html"
    model = Lead
    fields = "full_name", "phone_number", "email", "ad"
    success_url = reverse_lazy("leadsapp:leads_list")


class LeadDetailsView(PermissionRequiredMixin, DetailView):
    """Просмотр деталей потенциального пользователя"""

    permission_required = "leadsapp.view_lead"
    template_name = "leadsapp/leads_detail.html"
    model = Lead


class LeadUpdateView(PermissionRequiredMixin, UpdateView):
    """Редактирование потенциального пользователя"""

    permission_required = "leadsapp.change_lead"
    template_name = "leadsapp/leads_update.html"
    model = Lead
    fields = "full_name", "phone_number", "email", "ad"

    def get_success_url(self):
        """
        После успешного обновления 'потенциального пользователя',
        перенаправляемся на этот URL
        """
        return reverse(
            "leadsapp:leads_detail",
            kwargs={"pk": self.object.pk},
        )


class LeadDeleteView(PermissionRequiredMixin, DeleteView):
    """Удаление потенциального пользователя"""

    permission_required = "leadsapp.delete_lead"
    template_name = "leadsapp/leads_delete.html"
    model = Lead
    success_url = reverse_lazy("leadsapp:leads_list")

DjangoCRM/leadsapp/templates/leadsapp/leads_create.html
{% extends "leadsapp/base.html" %}

{% block body %}
<h2 class="fw-bold">Создание лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/leads/new/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

DjangoCRM/leadsapp/templates/leadsapp/leads_delete.html
{% extends "leadsapp/base.html" %}

{% block body %}
<h2 class="fw-bold">Удаление лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.full_name }}"?</p>
        <form method="POST" action="/leads/{{ object.pk }}/delete/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

DjangoCRM/leadsapp/templates/leadsapp/leads_detail.html
{% extends "leadsapp/base.html" %}

{% block body %}
<h2 class="fw-bold">Детальная информация о лиде</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ object.full_name }}</h5>
                <p class="card-text">{{ object.phone_number }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ object.email }}</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="/leads/{{ object.pk }}/edit" class="btn btn-primary">Редактировать</a>
                </div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="/leads/{{ lead.pk }}/delete" class="btn btn-danger">Удалить</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

DjangoCRM/leadsapp/templates/leadsapp/leads_list.html
{% extends "leadsapp/base.html" %}

{% block body %}
<h2 class="fw-bold">Лиды</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="/leads/new" class="btn btn-success p-2">Создать</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for lead in leads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="/leads/{{ lead.pk }}" class="text-decoration-none link-dark">{{ lead.full_name }}</a>
                <a href="/leads/{{ lead.pk }}/delete" class="btn btn-danger">Удалить</a>
                <a href="{% url 'customersapp:customers_create' %}?lead_id={{ lead.pk }}" class="btn btn-success p-2">Перевести в активного</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

DjangoCRM/leadsapp/templates/leadsapp/leads_update.html
{% extends "leadsapp/base.html" %}

{% block body %}
<h2 class="fw-bold">Редактирование лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST" action="/leads/{{ object.pk }}/edit/">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}